### ISSUE TITLE
cross-browser compatibility

### ISSUE THREAD

**Issue by mmore500** [mmore500/dishtiny#1]
@rodsan0 pointed out that he could only run the web viewer on chromium, not firefox

**Comment by rodsan0** [comment]
possibly related: https://github.com/emscripten-core/emscripten/issues/5559#issuecomment-327861660

**Comment by mmore500** [comment]
useful links from @rodsan0 

Wasm also has a way to set an initial and maximum memory size https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory

possible solution:
https://emscripten.org/docs/optimizing/Optimizing-Code.html#memory-growth

**Comment by mmore500** [comment]
fixed by @rodsan0 :tada:
