### ISSUE TITLE
Consistent button/view key title names

### ISSUE THREAD

**Issue by mmore500** [mmore500/dishtiny#3]
When I edited the `keys.toml` file, I updated some of the view names (e.g., bolded bolded text in the key's header item).

We need to make corresponding changes in `WebInterface.h` so that the generated button names match.

**Comment by rodsan0** [comment]
fixed by https://github.com/rodsan0/dishtiny/commit/5e9e85c5c3a16d56e62ecde590808a2c5e48a914
